[package]
name = "divvunspell"
version = "0.5.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[lib]
name = "divvunspell"
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
libc = "0.2"
memmap = "0.7.0"
byteorder = "1.3.2"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
serde-xml-rs = { version = "0.3.1", default-features = false }
zip = { version = "0.5", default-features = false }
unic-segment = "0.9.0"
unic-char-range = "0.9.0"
unic-char-property = "0.9.0"
parking_lot = "0.9.0"
hashbrown = { version = "0.6", features = ["serde"] }
tempdir = "0.3.7"
lifeguard = "0.6"
smol_str = { version = "0.1.13", features = ["serde"] }
box_format = { git = "https://github.com/bbqsrc/box", branch = "feature/ffi", default-features = false }
itertools = "0.8.0"
strsim = "0.9.2"
log = { version = "0.4.8" }
# cthulhu = { path = "../../cthulhu/cthulhu" }
# cursed = { path = "../../cthulhu/cursed" }
cthulhu = { git = "https://github.com/cthulhu-rs/cthulhu", branch = "feature/callback" }
cursed = { git = "https://github.com/cthulhu-rs/cthulhu", branch = "feature/callback" }

[features]
compression = ["zip/deflate"]
convert = []
ffi = []
